version: "3.8"

services:
  redis:
    image: redis
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data_redis
    command: redis-server --port 6379 --appendonly yes
